### ISSUE TITLE
2 issues with latest build(s) 

### ISSUE THREAD

**Issue by XeonG** [richardbiely/Voxelmetric#39]
so screen shots so 2 different issues.. one is with connectedblocks.. the texturing is broken

http://i.imgur.com/8hVAkaC.png

and the other issue is far worse and I think it cropped up in last years December update

basically flat block faces are being left behind on the bottom of a chunk.. instead of being removed.. and if you place the block below it, both the below chunk draws the top face, and also the above chunk draws the previous block face texture that was there...

  its  easier to just try it out yourself to see what I mean hopefully you can fix it soon, its been bothering me for a while but was thinking it was my own changes that had caused it, only the yesterday commits made me check out the original source to see if it had this this issue and as the above screenshot proves it does.

**Comment by richardbiely** [comment]
I know about these - work in progress

**Comment by XeonG** [comment]
ok cool

**Comment by XeonG** [comment]
Have you got any closer to finding the cause of the bugs? Not sure if I should just roll back to the pre december updates or wait for an update as I been wanting to release an update of my game to some testers but the voxel bugs with this are a bit off putting to leave in the build

**Comment by richardbiely** [comment]
I'm afraid I won't be able to find much time to work on Voxe(lmetric) at least till the second half of the month.

However, till then, you're always more then welcome to provide your own fix to any issue.:)

**Comment by XeonG** [comment]
oh ok appreciate the time frame on it, think I'll rollback then. Is it any one particular file or method that its caused in that you already know of?, that I could maybe try find a fix for? or is it likely a problem spread over multiple file changes from last years december commits?

**Comment by XeonG** [comment]
So I did find the workaround for one of the most annoying bugs.. It started with your commit here https://github.com/richardbiely/Voxelmetric/commit/d4122e96743dfad16d5d1ed888a09797f4c929ab

     // It is only necessary to perform the sychronization once when data is generated.
+            // All subsequend changes of blocks are automatically synchronized inside ChunkBlocks
+            if (!m_syncEdgeBlocks)
+                return;
+            m_syncEdgeBlocks = false;

That code is was causing all kinds of problems with geometry generation on subsequent block changes to the world, so I've just commented it out for now perhaps you missed something else?

Connectedblocks is still broken though haven't looked into it myself, hopefully you have time to work on the project again soon.

**Comment by richardbiely** [comment]
Thank you - the issue with faces should be fixed in b360998f559fe5922d260af9c23d2b36ce3e9a4b

As for the connected block textures - I think it has always been there. It simply manifested now that I made textures face the right way (hopefully :) ). I'll take a look at it when I have time.

For future issues, I would kindly like to ask you to create a separate issue for separate bugs rather then mixing them together. It is easier to maintain that way :)

**Comment by XeonG** [comment]
So you are saying the connected block textures just need fixing for it to work properly again?

**Comment by richardbiely** [comment]
Well, what I'm saying is that I think changing the code is necessary. Textures as such can remain as they are. I will have to put some time into it in order to verify my hypothesis. The code computing which connected block texture is to be used is not something which one understands at first glance.

**Comment by XeonG** [comment]
at multiple glances I still don't understand most this library ☺️

**Comment by superfrantv** [comment]
The texture Problem it think can be finished:

Open the texture and give it a invisible border.

**Comment by richardbiely** [comment]
The only thing that would do is improve your photoshop skills I'm afraid.
The issue here is that texture indexes do not match texture data. I don't want anybody modify their textures when it is a simple fix in the code.
